services:
  database:
    image: postgres
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT} 
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - library-network
  


  rabbitmq:
    image: "rabbitmq:3.13-rc-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672"  
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - library-network
 
  user-service:
    image: paarth123/userservice:v1
    container_name: api
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest    
    depends_on:
      rabbitmq:
        condition: service_healthy
      database:
        condition: service_started
    networks:
      - library-network
    ports:
      - "5002:5002"
    # restart: unless-stopped
    env_file:
      - .env  
    
  book-service:
    image: paarth123/bookservice:v1
    container_name: book-api
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}      
    depends_on:
      - database
      - rabbitmq
    networks:
      - library-network
    ports:
      - "5006:5006"
    # restart: unless-stopped
    env_file:
      - .env  

  borrow-service:
    image: paarth123/borrowservice:v1
    container_name: borrow-service
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest    
    depends_on:
      rabbitmq:
        condition: service_healthy
      database:
        condition: service_started
    networks:
      - library-network
    ports:
      - "7000:7000"  
    # restart: unless-stopped
    env_file:
      - .env



networks:
  library-network:
    name: library-network

volumes:
  db_data:



