apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/library-network: "true"
        io.kompose.service: user-service
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: library
            - name: POSTGRES_HOST
              value: database
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: user
            - name: RABBITMQ_DEFAULT_PASS
              value: guest
            - name: RABBITMQ_DEFAULT_PASSWORD
              value: guest
            - name: RABBITMQ_DEFAULT_USER
              value: guest
          image: paarth123/userservice:v1
          name: api
          ports:
            - containerPort: 5002
              hostPort: 5002
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
