version: '3.8'

services:
  database:
    image: postgres
    container_name: database 
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - library-network
    env_file:
      - .env
  


  rabbitmq:
    image: "rabbitmq:3.13-rc-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672"  
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - library-network
 
  user-service:
    build: ./UserService
    container_name: api  
    depends_on:
      rabbitmq:
        condition: service_healthy
      database:
        condition: service_started
    networks:
      - library-network
    ports:
      - "5002:5002"
    # restart: unless-stopped
    env_file:
      - .env  
    
  book-service:
    build: ./BookService
    container_name: book-api      
    depends_on:
      - database
      - rabbitmq
    networks:
      - library-network
    ports:
      - "5006:5006"
    restart: unless-stopped
    env_file:
      - .env  

  borrow-service:
    build: ./BorrowService
    container_name: borrow-service   
    depends_on:
      rabbitmq:
        condition: service_healthy
      database:
        condition: service_started
    networks:
      - library-network
    ports:
      - "7000:7000"  
    restart: unless-stopped
    env_file:
      - .env



networks:
  library-network:
    name: library-network

volumes:
  db_data:



